version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  indexing_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./documents:/app/documents
    depends_on:
      - elasticsearch
  search_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
volumes:
  esdata:
